# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/djl/cpps/CppLearningLab

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/djl/cpps/CppLearningLab

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/djl/cpps/CppLearningLab/CMakeFiles /home/djl/cpps/CppLearningLab//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/djl/cpps/CppLearningLab/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named base_object

# Build rule for target.
base_object: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 base_object
.PHONY : base_object

# fast build rule for target.
base_object/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/base_object.dir/build.make src/CMakeFiles/base_object.dir/build
.PHONY : base_object/fast

#=============================================================================
# Target rules for targets named convert_type

# Build rule for target.
convert_type: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 convert_type
.PHONY : convert_type

# fast build rule for target.
convert_type/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/convert_type.dir/build.make src/CMakeFiles/convert_type.dir/build
.PHONY : convert_type/fast

#=============================================================================
# Target rules for targets named function_object

# Build rule for target.
function_object: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 function_object
.PHONY : function_object

# fast build rule for target.
function_object/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/function_object.dir/build.make src/CMakeFiles/function_object.dir/build
.PHONY : function_object/fast

#=============================================================================
# Target rules for targets named function_template

# Build rule for target.
function_template: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 function_template
.PHONY : function_template

# fast build rule for target.
function_template/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/function_template.dir/build.make src/CMakeFiles/function_template.dir/build
.PHONY : function_template/fast

#=============================================================================
# Target rules for targets named m_any

# Build rule for target.
m_any: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 m_any
.PHONY : m_any

# fast build rule for target.
m_any/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/m_any.dir/build.make src/CMakeFiles/m_any.dir/build
.PHONY : m_any/fast

#=============================================================================
# Target rules for targets named m_sizeof

# Build rule for target.
m_sizeof: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 m_sizeof
.PHONY : m_sizeof

# fast build rule for target.
m_sizeof/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/m_sizeof.dir/build.make src/CMakeFiles/m_sizeof.dir/build
.PHONY : m_sizeof/fast

#=============================================================================
# Target rules for targets named m_string

# Build rule for target.
m_string: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 m_string
.PHONY : m_string

# fast build rule for target.
m_string/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/m_string.dir/build.make src/CMakeFiles/m_string.dir/build
.PHONY : m_string/fast

#=============================================================================
# Target rules for targets named object_init

# Build rule for target.
object_init: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 object_init
.PHONY : object_init

# fast build rule for target.
object_init/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/object_init.dir/build.make src/CMakeFiles/object_init.dir/build
.PHONY : object_init/fast

#=============================================================================
# Target rules for targets named object_pool

# Build rule for target.
object_pool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 object_pool
.PHONY : object_pool

# fast build rule for target.
object_pool/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/object_pool.dir/build.make src/CMakeFiles/object_pool.dir/build
.PHONY : object_pool/fast

#=============================================================================
# Target rules for targets named iterator

# Build rule for target.
iterator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iterator
.PHONY : iterator

# fast build rule for target.
iterator/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/iterator.dir/build.make src/CMakeFiles/iterator.dir/build
.PHONY : iterator/fast

#=============================================================================
# Target rules for targets named sort_vector

# Build rule for target.
sort_vector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sort_vector
.PHONY : sort_vector

# fast build rule for target.
sort_vector/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/sort_vector.dir/build.make src/CMakeFiles/sort_vector.dir/build
.PHONY : sort_vector/fast

#=============================================================================
# Target rules for targets named templates_vector

# Build rule for target.
templates_vector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 templates_vector
.PHONY : templates_vector

# fast build rule for target.
templates_vector/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/templates_vector.dir/build.make src/CMakeFiles/templates_vector.dir/build
.PHONY : templates_vector/fast

#=============================================================================
# Target rules for targets named vector

# Build rule for target.
vector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vector
.PHONY : vector

# fast build rule for target.
vector/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/vector.dir/build.make src/CMakeFiles/vector.dir/build
.PHONY : vector/fast

#=============================================================================
# Target rules for targets named roman_to_Intege

# Build rule for target.
roman_to_Intege: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 roman_to_Intege
.PHONY : roman_to_Intege

# fast build rule for target.
roman_to_Intege/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/roman_to_Intege.dir/build.make src/CMakeFiles/roman_to_Intege.dir/build
.PHONY : roman_to_Intege/fast

#=============================================================================
# Target rules for targets named m_condition

# Build rule for target.
m_condition: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 m_condition
.PHONY : m_condition

# fast build rule for target.
m_condition/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/m_condition.dir/build.make src/CMakeFiles/m_condition.dir/build
.PHONY : m_condition/fast

#=============================================================================
# Target rules for targets named m_mutex_unique_lock

# Build rule for target.
m_mutex_unique_lock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 m_mutex_unique_lock
.PHONY : m_mutex_unique_lock

# fast build rule for target.
m_mutex_unique_lock/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/m_mutex_unique_lock.dir/build.make src/CMakeFiles/m_mutex_unique_lock.dir/build
.PHONY : m_mutex_unique_lock/fast

#=============================================================================
# Target rules for targets named m_thread

# Build rule for target.
m_thread: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 m_thread
.PHONY : m_thread

# fast build rule for target.
m_thread/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/m_thread.dir/build.make src/CMakeFiles/m_thread.dir/build
.PHONY : m_thread/fast

#=============================================================================
# Target rules for targets named multiprocess

# Build rule for target.
multiprocess: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 multiprocess
.PHONY : multiprocess

# fast build rule for target.
multiprocess/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/multiprocess.dir/build.make src/CMakeFiles/multiprocess.dir/build
.PHONY : multiprocess/fast

#=============================================================================
# Target rules for targets named blocking_io

# Build rule for target.
blocking_io: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blocking_io
.PHONY : blocking_io

# fast build rule for target.
blocking_io/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/blocking_io.dir/build.make src/CMakeFiles/blocking_io.dir/build
.PHONY : blocking_io/fast

#=============================================================================
# Target rules for targets named epoll

# Build rule for target.
epoll: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 epoll
.PHONY : epoll

# fast build rule for target.
epoll/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/epoll.dir/build.make src/CMakeFiles/epoll.dir/build
.PHONY : epoll/fast

#=============================================================================
# Target rules for targets named noblocking_io

# Build rule for target.
noblocking_io: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 noblocking_io
.PHONY : noblocking_io

# fast build rule for target.
noblocking_io/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/noblocking_io.dir/build.make src/CMakeFiles/noblocking_io.dir/build
.PHONY : noblocking_io/fast

#=============================================================================
# Target rules for targets named poll

# Build rule for target.
poll: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 poll
.PHONY : poll

# fast build rule for target.
poll/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/poll.dir/build.make src/CMakeFiles/poll.dir/build
.PHONY : poll/fast

#=============================================================================
# Target rules for targets named select

# Build rule for target.
select: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 select
.PHONY : select

# fast build rule for target.
select/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/select.dir/build.make src/CMakeFiles/select.dir/build
.PHONY : select/fast

#=============================================================================
# Target rules for targets named question1

# Build rule for target.
question1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 question1
.PHONY : question1

# fast build rule for target.
question1/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/question1.dir/build.make src/CMakeFiles/question1.dir/build
.PHONY : question1/fast

#=============================================================================
# Target rules for targets named m_smart_pointers

# Build rule for target.
m_smart_pointers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 m_smart_pointers
.PHONY : m_smart_pointers

# fast build rule for target.
m_smart_pointers/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/m_smart_pointers.dir/build.make src/CMakeFiles/m_smart_pointers.dir/build
.PHONY : m_smart_pointers/fast

#=============================================================================
# Target rules for targets named m_lambada

# Build rule for target.
m_lambada: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 m_lambada
.PHONY : m_lambada

# fast build rule for target.
m_lambada/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/m_lambada.dir/build.make src/CMakeFiles/m_lambada.dir/build
.PHONY : m_lambada/fast

#=============================================================================
# Target rules for targets named meckcheck

# Build rule for target.
meckcheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 meckcheck
.PHONY : meckcheck

# fast build rule for target.
meckcheck/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/meckcheck.dir/build.make src/CMakeFiles/meckcheck.dir/build
.PHONY : meckcheck/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... base_object"
	@echo "... blocking_io"
	@echo "... convert_type"
	@echo "... epoll"
	@echo "... function_object"
	@echo "... function_template"
	@echo "... iterator"
	@echo "... m_any"
	@echo "... m_condition"
	@echo "... m_lambada"
	@echo "... m_mutex_unique_lock"
	@echo "... m_sizeof"
	@echo "... m_smart_pointers"
	@echo "... m_string"
	@echo "... m_thread"
	@echo "... meckcheck"
	@echo "... multiprocess"
	@echo "... noblocking_io"
	@echo "... object_init"
	@echo "... object_pool"
	@echo "... poll"
	@echo "... question1"
	@echo "... roman_to_Intege"
	@echo "... select"
	@echo "... sort_vector"
	@echo "... templates_vector"
	@echo "... vector"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

